import React from "react";
import { useEffect, useState } from "react";
import { useLoginMutation } from "./authApiSlice";
import { setToken } from "./authSlice";
import { useDispatch } from "react-redux";
import { useNavigate } from 'react-router-dom';
import Avatar from '@mui/material/Avatar';
import Button from '@mui/material/Button';
import CssBaseline from '@mui/material/CssBaseline';
import TextField from '@mui/material/TextField';
import { Link } from 'react-router-dom'
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import LockOutlinedIcon from '@mui/icons-material/LockOutlined';
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import DecodeToken from "./decodeToken";

/**
 * Login component for handling user authentication.
 * 
 * This component utilizes React hooks such as useEffect, useDispatch, and useState to manage the login process.
 * It also uses custom hooks generated by GraphQL Code Generator for handling GraphQL mutations.
 * 
 * When the user submits the login form, it sends a request to the server to authenticate the user.
 * If the authentication is successful, it stores the user token in the Redux store and navigates the user to the home page.
 * */
const Login = () => {
  // Importing necessary hooks and functions from libraries and custom modules
  const dispatch = useDispatch() // Redux hook for dispatching actions
  const navigate = useNavigate() // React Router hook for navigation
  const [loginFunc, { isError, error, isSuccess, isLoading, data }] = useLoginMutation()  // Custom hook for handling login mutation
  // Effect hook to handle side effects after component renders
  useEffect(() => {
    // If login is successful, store token and navigate to home page
    if (isSuccess) {
      dispatch(setToken(data)) // Dispatching Redux action to store user token
      const role = DecodeToken().roles; // Decoding token to extract user role
      console.log(`role is ${role} `); // Logging user role
      navigate("/HomePage", { replace: true }) // Navigating user to home page
    }
  }, [isSuccess]) // Dependency array to run effect only when isSuccess changes

  // Function to handle form submission
  const handleSubmit = (event) => {
    event.preventDefault(); // Prevent default form submission
    const data = new FormData(event.currentTarget);
    loginFunc({
      username: data.get('username'),
      password: data.get('password')
    })
    console.log({
      username: data.get('username'),
      password: data.get('password'),
    });

  };

  // Function for rendering copyright information
  function Copyright(props) {
    return (
      <Typography variant="body2" color="text.secondary" align="center" {...props}>
        {'Our Site © '}
        <Link color="inherit" href="https://mui.com/">
          Sari & Yaeli        </Link>{' '}
        {new Date().getFullYear()}
        {'.'}
      </Typography>
    );
  }

  // Creating a default MUI theme
  const defaultTheme = createTheme();

  return (
    <ThemeProvider theme={defaultTheme} >
      <Container component="main" maxWidth="xs">
        <CssBaseline />
        <Box
          sx={{
            marginTop: 8,
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
          }}
        >
          <Avatar sx={{ m: 1, bgcolor: 'secondary.main' }}>
            <LockOutlinedIcon />
          </Avatar>
          <Typography component="h1" variant="h5">
            כניסה
          </Typography>
          <Box component="form" onSubmit={handleSubmit} noValidate sx={{ mt: 1 }}>
            <TextField
              dir='rtl'
              margin="normal"
              required
              fullWidth
              id="username"
              label="שם משתמש"
              name="username"
              autoComplete="username"
              //check it....
              autoFocus
            />
            <TextField
              dir='rtl'
              margin="normal"
              required
              fullWidth
              name="password"
              label="סיסמא"
              type="password"
              id="password"
              autoComplete="current-password"
            />
            <Button
              dir='rtl'
              type="submit"
              fullWidth
              variant="contained"
              sx={{ mt: 3, mb: 2 }}
            >
              כניסה
            </Button>
            <Grid container>
              <Grid item xs>
                <Link to={'/Register'} variant="body2" >
                  {"הרשמת מנהלים  "}
                </Link>
              </Grid>
              <Grid item>
                <Link to={'/SignUp'}>
                  {"\n Don't have an account? "}
                  <span style={{ textDecoration: 'underline' }}>Sign Up</span>
                </Link>
              </Grid>
            </Grid>
          </Box>
        </Box>
        <Copyright sx={{ mt: 8, mb: 4 }} />
      </Container>
    </ThemeProvider>
  );
};
export default Login;